# Form implementation generated from reading ui file 'UI/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 661)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color: #F0F0F0;\n"
"}\n"
"#frame{\n"
"    background-color: #f5f5f5;\n"
"}\n"
"#frame2{\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QPushButton{\n"
"  background-color: #333333;\n"
"  border: none;\n"
"  border-radius: 6px;\n"
"  color: #cccccc;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  padding: 4px 12px;\n"
"  height:40px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51, 0.5);\n"
"     text-decoration: none;\n"
"}\n"
"QPushButton:focus{\n"
"     outline: 1px transparent;\n"
"}\n"
"QLabel{\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_5.setStyleSheet("\n"
"QPushButton{\n"
"  background-color: #333333;\n"
"  border: none;\n"
"  border-radius: 75px;\n"
"  color: #cccccc;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  line-height: 19px;\n"
"  list-style: none;\n"
"  padding: 4px 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51, 0.5);\n"
"     text-decoration: none;\n"
"}\n"
"QPushButton:focus{\n"
"     outline: 1px transparent;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.recordBtn = QtWidgets.QPushButton(parent=self.frame_5)
        self.recordBtn.setMinimumSize(QtCore.QSize(150, 150))
        self.recordBtn.setMaximumSize(QtCore.QSize(150, 150))
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout_3.addWidget(self.recordBtn)
        spacerItem2 = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.outputLabel = QtWidgets.QLabel(parent=self.frame_6)
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_4.addWidget(self.outputLabel)
        spacerItem4 = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 220))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.graphOneWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.graphOneWidget.setMinimumSize(QtCore.QSize(250, 200))
        self.graphOneWidget.setObjectName("graphOneWidget")
        self.horizontalLayout_2.addWidget(self.graphOneWidget)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.graphTwoWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.graphTwoWidget.setMinimumSize(QtCore.QSize(250, 200))
        self.graphTwoWidget.setObjectName("graphTwoWidget")
        self.horizontalLayout_2.addWidget(self.graphTwoWidget)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.accessTabel = QtWidgets.QTableWidget(parent=self.frame_2)
        self.accessTabel.setObjectName("accessTabel")
        self.accessTabel.setColumnCount(0)
        self.accessTabel.setRowCount(0)
        self.verticalLayout_3.addWidget(self.accessTabel)
        self.sentenceTabel = QtWidgets.QTableWidget(parent=self.frame_2)
        self.sentenceTabel.setObjectName("sentenceTabel")
        self.sentenceTabel.setColumnCount(0)
        self.sentenceTabel.setRowCount(0)
        self.verticalLayout_3.addWidget(self.sentenceTabel)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordBtn.setText(_translate("MainWindow", "Record"))
        self.outputLabel.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
